if &compatible
	set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
	call dein#begin('~/.cache/dein')

	call dein#add('~/.cache/dein')
	call dein#add('Shougo/deoplete.nvim')
	if !has('nvim')
		call dein#add('roxma/nvim-yarp')
		call dein#add('roxma/vim-hug-neovim-rpc')
	endif

	call dein#add('itchyny/lightline.vim')
	call dein#add('tpope/vim-surround')
	call dein#add('tpope/vim-obsession')
	call dein#add('easymotion/vim-easymotion')
	call dein#add('ludovicchabant/vim-gutentags')
	call dein#add('vim-scripts/indentpython.vim')
	call dein#add('jmcantrell/vim-virtualenv')
	call dein#add('lervag/vimtex')
	call dein#add('jlanzarotta/bufexplorer')
	call dein#add('kien/ctrlp.vim')
	call dein#add('tpope/vim-fugitive')
	call dein#add('junegunn/gv.vim')
	call dein#add('airblade/vim-gitgutter')
	call dein#add('vim-syntastic/syntastic')
	call dein#add('nvie/vim-flake8')
	call dein#add('scrooloose/nerdTree')
	call dein#add('jistr/vim-nerdtree-tabs')
	call dein#add('scrooloose/nerdcommenter')
	call dein#add('raimondi/delimitmate')
	call dein#add('maxbrunsfeld/vim-yankstack')
	call dein#add('terryma/vim-multiple-cursors')
	call dein#add('christoomey/vim-tmux-navigator')
	call dein#add('rust-lang/rust.vim')
	call dein#add('flazz/vim-colorschemes')
	call dein#add('peterhoeg/vim-qml')
	call dein#add('mhinz/vim-startify')
	call dein#add('Shougo/unite.vim')
	call dein#add('Shougo/vimfiler.vim')
	call dein#add('shinchu/lightline-gruvbox.vim')
	call dein#add('haya14busa/incsearch.vim')
	call dein#add('sheerun/vim-polyglot')
	call dein#add('w0rp/ale')

	let g:deoplete#enable_at_startup = 1
	call dein#end()
	call dein#save_state()
endif

filetype plugin indent on
syntax enable

set t_Co=256

" Python highlighting
let python_highlight_all=1

set background=dark

" Jump to the last position when reopening a file
"if has("autocmd")
"au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

set showcmd		" Show (partial) command in status line.
set smartcase	" Do smart case matching
set autowrite	" Automatically save before commands like :next and :make
set hidden		" Hide buffers when they are abandoned

set spell spelllang=en_us
set spellfile=~/.vim/spell/en.utf-8.add
set nospell

set laststatus=2

set hlsearch

set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'

set switchbuf=useopen,usetab,newtab
set ignorecase
set smartcase

try
	set undodir=~/.vim_runtime/temp_dirs/undodir
	set undofile
catch
endtry

" ignore specified files in NERDTree
let NERDTreeIgnore=['\.pyc$', '\~$']

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 2
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_aggregate_errors = 1

" remove header from startify
let g:startify_custom_header = []

" solve meta key not working
let c='a'
set timeout ttimeoutlen=50

let mapleader = ","
let g:mapleader = ","

set encoding=utf-8

" Set 7 lines to the cursor - when moving vertically using j/k
set so=7

" sudo save to avoid permission denied
command W w !sudo tee % > /dev/null

" Always show current position
set ruler

set nu
" Relative numbers when not in insert mode,
" normal line numbers when in insert mode
augroup numbertoggle
	autocmd!
	autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
	autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Don't redraw while executing macros (good performance config)
set lazyredraw

" For regular expressions turn magic on
set magic

set nobackup
set nowb
set noswapfile

" Use spaces instead of tabs
set noexpandtab

" Be smart when using tabs
set smarttab

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=4

" Access system clipboard
set clipboard=unnamed

" python PEP8 indentation standards
au BufNewFile,BufRead *.py
			\ set tabstop=4 |
			\ set softtabstop=4 |
			\ set shiftwidth=4 |
			\ set textwidth=79 |
			\ set expandtab |
			\ set autoindent |
			\ set fileformat=unix

" 2 space tab indentation
au BufNewFile,BufRead *.html,*.tex,*.vim
			\ set tabstop=2 |
			\ set softtabstop=2 |
			\ set shiftwidth=2

" Highlight unecessary whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Useful mappings for managing tabs
map <leader>tn :tabnew .<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
map <leader>t<leader> :tabnext

" for splits
set splitright
set splitbelow
map <leader>vp :vsplit .<cr>
map <leader>hp :split .<cr>

" Insert empty line
nmap <C-o> o<Esc>

" Let 'tl' toggle between this and the last accessed tab
let g:lasttab = 1
nmap <Leader>tl :exe "tabn ".g:lasttab<CR>
au TabLeave * let g:lasttab = tabpagenr()

" Opens a new tab with the current buffer's path
" Super useful when editing files in the same directory
map <leader>te :tabedit <c-r>=expand("%:p:h")<cr>/

" Switch CWD to the directory of the open buffer
map <leader>cd :cd %:p:h<cr>:pwd<cr>

" Specify the behavior when switching between buffers
try
	set switchbuf=useopen,usetab,newtab
	set stal=2
catch
endtry

" Delete trailing white space on save
func! DeleteTrailingWS()
	exe "normal mz"
	%s/\s\+$//e
	exe "normal `z"
endfunc
autocmd BufWrite * :call DeleteTrailingWS()

" Toggle and untoggle spell checking
map <leader>ss :setlocal spell!<cr>

" incsearch remappings
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

" incsearch intelligent nohl
set hlsearch
let g:incsearch#auto_nohlsearch = 1
map n  <Plug>(incsearch-nohl-n)
map N  <Plug>(incsearch-nohl-N)
map *  <Plug>(incsearch-nohl-*)
map #  <Plug>(incsearch-nohl-#)
map g* <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)

set path=.,,**

colorscheme gruvbox

let g:lightline = {}
let g:lightline.colorscheme = 'gruvbox'
